# Generated by Django 4.0.5 on 2022-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('nombrePattes', models.IntegerField(max_length=4)),
                ('dureeVie', models.IntegerField(max_length=3)),
                ('image_url', models.ImageField(null=True, blank=True, upload_to="images/")),
                ('description', models.TextField()),
            ],
        ),
    ]
