# Generated by Django 4.0.5 on 2022-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeAnimaux', '0002_alter_animaux_dureevie_alter_animaux_nombrepattes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaux',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
