# Generated by Django 4.0.5 on 2022-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeAnimaux', '0003_alter_animaux_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaux',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
