# Generated by Django 4.0.5 on 2022-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeAnimaux', '0004_alter_animaux_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('nomScientifique', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=2000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='animaux',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
